name: wan_android
description: Flutter版WanAndroid.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  base_library:
    git:
      url: git://github.com/fengwuhen/base_library.git
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^1.0.1
  fluttertoast: ^3.1.3
  flutter_webview_plugin: ^0.3.10+1
  cached_network_image: ^2.0.0
  url_launcher: ^5.4.1
  pull_to_refresh: ^1.5.8
  fluro: ^1.5.1
  share: ^0.6.3+5
  date_format: ^1.0.8

flutter:
  uses-material-design: true